//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPWeb_ServerEntities : DbContext
    {
        public ERPWeb_ServerEntities()
            : base("name=ERPWeb_ServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbAlmacen> tbAlmacen { get; set; }
        public virtual DbSet<tbArticulo> tbArticulo { get; set; }
        public virtual DbSet<tbArticuloXProveedor> tbArticuloXProveedor { get; set; }
        public virtual DbSet<tbCiudades> tbCiudades { get; set; }
        public virtual DbSet<tbClaseArticulo> tbClaseArticulo { get; set; }
        public virtual DbSet<tbClasificacion> tbClasificacion { get; set; }
        public virtual DbSet<tbColor> tbColor { get; set; }
        public virtual DbSet<tbComprador> tbComprador { get; set; }
        public virtual DbSet<tbConsumoDet> tbConsumoDet { get; set; }
        public virtual DbSet<tbConsumoEnc> tbConsumoEnc { get; set; }
        public virtual DbSet<tbContactoProv> tbContactoProv { get; set; }
        public virtual DbSet<tbEmpresa> tbEmpresa { get; set; }
        public virtual DbSet<tbEstadoOC> tbEstadoOC { get; set; }
        public virtual DbSet<tbEstados> tbEstados { get; set; }
        public virtual DbSet<tbEstatus> tbEstatus { get; set; }
        public virtual DbSet<tbEstatusOC> tbEstatusOC { get; set; }
        public virtual DbSet<tbExistenciaDesglose> tbExistenciaDesglose { get; set; }
        public virtual DbSet<tbExistenciaEnc> tbExistenciaEnc { get; set; }
        public virtual DbSet<tbGrupoProducto> tbGrupoProducto { get; set; }
        public virtual DbSet<tbGrupoProv> tbGrupoProv { get; set; }
        public virtual DbSet<tbInventarioFisicoDet> tbInventarioFisicoDet { get; set; }
        public virtual DbSet<tbInventarioFisicoEnc> tbInventarioFisicoEnc { get; set; }
        public virtual DbSet<tbLenguajes> tbLenguajes { get; set; }
        public virtual DbSet<tbLinea> tbLinea { get; set; }
        public virtual DbSet<tbMaximoMinimo> tbMaximoMinimo { get; set; }
        public virtual DbSet<tbModelo> tbModelo { get; set; }
        public virtual DbSet<tbMoneda> tbMoneda { get; set; }
        public virtual DbSet<tbMotivosTransacciones> tbMotivosTransacciones { get; set; }
        public virtual DbSet<tbOrdenCompraDesglose> tbOrdenCompraDesglose { get; set; }
        public virtual DbSet<tbOrdenCompraDet> tbOrdenCompraDet { get; set; }
        public virtual DbSet<tbOrdenCompraDetDesglose> tbOrdenCompraDetDesglose { get; set; }
        public virtual DbSet<tbOrdenCompraEnc> tbOrdenCompraEnc { get; set; }
        public virtual DbSet<tbOrdenGasto> tbOrdenGasto { get; set; }
        public virtual DbSet<tbPackingEnc> tbPackingEnc { get; set; }
        public virtual DbSet<tbPaises> tbPaises { get; set; }
        public virtual DbSet<tbPartner> tbPartner { get; set; }
        public virtual DbSet<tbPlazosPagos> tbPlazosPagos { get; set; }
        public virtual DbSet<tbPresentacion> tbPresentacion { get; set; }
        public virtual DbSet<tbProrrateo> tbProrrateo { get; set; }
        public virtual DbSet<tbProveedor> tbProveedor { get; set; }
        public virtual DbSet<tbRegistroMovimiento> tbRegistroMovimiento { get; set; }
        public virtual DbSet<tbSolicitudTransDet> tbSolicitudTransDet { get; set; }
        public virtual DbSet<tbSolicitudTransEnc> tbSolicitudTransEnc { get; set; }
        public virtual DbSet<tbSolTransDetDesglose> tbSolTransDetDesglose { get; set; }
        public virtual DbSet<tbSubClasificacion> tbSubClasificacion { get; set; }
        public virtual DbSet<tbTipoCambio> tbTipoCambio { get; set; }
        public virtual DbSet<tbTipoCodigo> tbTipoCodigo { get; set; }
        public virtual DbSet<tbTipoGasto> tbTipoGasto { get; set; }
        public virtual DbSet<tbTipoMovimiento> tbTipoMovimiento { get; set; }
        public virtual DbSet<tbTipoTela> tbTipoTela { get; set; }
        public virtual DbSet<tbTransferencia> tbTransferencia { get; set; }
        public virtual DbSet<tbTraspasoAlmacenes> tbTraspasoAlmacenes { get; set; }
        public virtual DbSet<tbUbicacion> tbUbicacion { get; set; }
        public virtual DbSet<tbUnidadMedida> tbUnidadMedida { get; set; }
        public virtual DbSet<tbUnidadMedidaConversion> tbUnidadMedidaConversion { get; set; }
        public virtual DbSet<EpicorLive_UserFile> EpicorLive_UserFile { get; set; }
        public virtual DbSet<T_Menu> T_Menu { get; set; }
        public virtual DbSet<T_MenuDetalle> T_MenuDetalle { get; set; }
        public virtual DbSet<T_Rol> T_Rol { get; set; }
        public virtual DbSet<tbMenu> tbMenu { get; set; }
        public virtual DbSet<tbMenuDtl> tbMenuDtl { get; set; }
        public virtual DbSet<TbRol> TbRol { get; set; }
        public virtual DbSet<TbUsuario> TbUsuario { get; set; }
        public virtual DbSet<tbUsuarioLineas> tbUsuarioLineas { get; set; }
    }
}
