//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbArticulo
    {
        public int intArticuloId { get; set; }
        public Nullable<int> intEmpresa { get; set; }
        public string strPartNum { get; set; }
        public string strDescripcion { get; set; }
        public Nullable<int> intTipoCodigo { get; set; }
        public string strCodigoSat { get; set; }
        public Nullable<bool> IsBorrado { get; set; }
        public Nullable<int> intClase { get; set; }
        public Nullable<int> intCodigoProducto { get; set; }
        public string strObservaciones { get; set; }
        public Nullable<int> intClasificacion { get; set; }
        public Nullable<int> intProvPredeterminado { get; set; }
        public Nullable<bool> IsSeriado { get; set; }
        public Nullable<decimal> decAnchoRollo { get; set; }
        public Nullable<decimal> decCostoPromedio { get; set; }
        public Nullable<int> intUltimaOrden { get; set; }
        public Nullable<int> intSubClasificacion { get; set; }
        public Nullable<int> intLinea { get; set; }
        public Nullable<int> intModelo { get; set; }
        public Nullable<int> intColor { get; set; }
        public Nullable<int> intPresentacion { get; set; }
        public Nullable<int> intUMCompra { get; set; }
        public Nullable<int> intUMVenta { get; set; }
        public Nullable<int> intUMInventario { get; set; }
        public Nullable<int> intUMPresentacion { get; set; }
        public Nullable<int> intUMSat { get; set; }
        public Nullable<decimal> decGastosImportacion { get; set; }
        public Nullable<decimal> decFletes { get; set; }
        public Nullable<decimal> decArancel { get; set; }
        public Nullable<decimal> decImpuestoTotal { get; set; }
        public Nullable<decimal> decUltimoCosto { get; set; }
        public Nullable<decimal> decCostoEstandar { get; set; }
        public Nullable<decimal> decInventarioMin { get; set; }
        public Nullable<decimal> decInventarioMax { get; set; }
        public Nullable<decimal> decPrecioBaseLista { get; set; }
        public Nullable<int> intTiempoEspera { get; set; }
        public Nullable<decimal> decCostoLABMtyPesos { get; set; }
        public Nullable<decimal> decCostoLABMtyDolares { get; set; }
        public Nullable<decimal> decPesoPieza { get; set; }
        public Nullable<decimal> decInventarioSeguridad { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
        public Nullable<int> intPais { get; set; }
        public Nullable<decimal> decCostoPromMaterial { get; set; }
        public Nullable<decimal> decGastosCostoPromedio { get; set; }
        public Nullable<decimal> decUltimoCostoMaterial { get; set; }
        public Nullable<decimal> decGastosUltimoCosto { get; set; }
        public Nullable<decimal> decCostoEstandarMaterial { get; set; }
        public Nullable<decimal> decGastosCostoEstandar { get; set; }
        public string strPartNumLegacy { get; set; }
        public Nullable<bool> IsActivo { get; set; }
    }
}
