//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbArticuloXProveedor
    {
        public int intArticuloProvId { get; set; }
        public Nullable<int> intEmpresa { get; set; }
        public Nullable<int> intProveedor { get; set; }
        public string strPartNumProv { get; set; }
        public string strDescripcionProv { get; set; }
        public Nullable<bool> IsBorrado { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
        public string strObservaciones { get; set; }
        public Nullable<int> intArticulo { get; set; }
        public Nullable<decimal> decPrecioLista { get; set; }
        public Nullable<int> intTiempoEspera { get; set; }
        public Nullable<int> intProveedorPred { get; set; }
        public Nullable<bool> IsActivo { get; set; }
    }
}
