//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmpresa
    {
        public int intEmpresaId { get; set; }
        public string strEmpresa { get; set; }
        public string strNombre { get; set; }
        public string strDireccion1 { get; set; }
        public string strDireccion2 { get; set; }
        public string strCiudad { get; set; }
        public string strEstado { get; set; }
        public string strCP { get; set; }
        public string strPais { get; set; }
        public string strTelefono { get; set; }
        public string strFax { get; set; }
        public string strRFC { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<int> intActivo { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
        public Nullable<bool> IsBorrado { get; set; }
    }
}
