//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbExistenciaEnc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbExistenciaEnc()
        {
            this.tbExistenciaDesglose = new HashSet<tbExistenciaDesglose>();
        }
    
        public Nullable<int> intEmpresa { get; set; }
        public int intExistenciaId { get; set; }
        public Nullable<int> intArticulo { get; set; }
        public Nullable<int> intUnidadMedida { get; set; }
        public Nullable<int> intAlmacen { get; set; }
        public Nullable<int> intUbicacion { get; set; }
        public Nullable<decimal> decExistencia { get; set; }
        public Nullable<decimal> decCosto { get; set; }
        public Nullable<bool> IsSeriado { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
        public Nullable<decimal> decConvertido { get; set; }
    
        public virtual tbAlmacen tbAlmacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbExistenciaDesglose> tbExistenciaDesglose { get; set; }
    }
}
