//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbExistenciaDesglose
    {
        public Nullable<int> intExistenciaEnc { get; set; }
        public int intExistenciaDesglose { get; set; }
        public Nullable<int> intAlmacen { get; set; }
        public Nullable<int> intUbicacion { get; set; }
        public Nullable<int> intArticulo { get; set; }
        public Nullable<int> intCantidad { get; set; }
        public Nullable<int> intUMInventario { get; set; }
        public Nullable<decimal> decCantidadOriginal { get; set; }
        public Nullable<int> intUMPresentacion { get; set; }
        public Nullable<decimal> decExistencia { get; set; }
        public Nullable<int> intOrden { get; set; }
        public Nullable<bool> IsConvertido { get; set; }
        public string strNumeroSerie { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
        public Nullable<int> intProveedor { get; set; }
        public Nullable<bool> IsMarcado { get; set; }
        public Nullable<bool> IsImpreso { get; set; }
        public string strUsuarioImprime { get; set; }
    
        public virtual tbExistenciaEnc tbExistenciaEnc { get; set; }
    }
}
