//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInventarioFisicoDet
    {
        public int intInventarioDet { get; set; }
        public Nullable<int> intInventarioEnc { get; set; }
        public Nullable<int> intAlmacen { get; set; }
        public Nullable<int> intUbicacion { get; set; }
        public Nullable<int> intArticulo { get; set; }
        public string strSerie { get; set; }
        public Nullable<int> intCantidad { get; set; }
        public Nullable<int> intUMPresentacion { get; set; }
        public Nullable<decimal> decCantidad { get; set; }
        public Nullable<int> intUMInventario { get; set; }
        public Nullable<int> intCantidadReal { get; set; }
        public Nullable<decimal> decCantidadReal { get; set; }
        public Nullable<bool> IsVerificado { get; set; }
        public Nullable<bool> IsAjustado { get; set; }
        public string strComentarios { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
        public Nullable<bool> IsBorrado { get; set; }
    }
}
