//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMaximoMinimo
    {
        public int intMaxMin { get; set; }
        public Nullable<int> intEmpresa { get; set; }
        public Nullable<int> intAlmacen { get; set; }
        public Nullable<int> intUbicacion { get; set; }
        public Nullable<int> intArticulo { get; set; }
        public Nullable<decimal> decMinimo { get; set; }
        public Nullable<decimal> decMaximo { get; set; }
        public Nullable<decimal> decReorden { get; set; }
        public Nullable<bool> IsActivo { get; set; }
        public Nullable<bool> IsBorrado { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
    }
}
