//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMenu
    {
        public int IDMenu { get; set; }
        public string Descripcion { get; set; }
        public string Viewer { get; set; }
        public string Controller { get; set; }
        public string Parametro { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<bool> IsNode { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> IsActivo { get; set; }
    }
}
