//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrdenGasto
    {
        public int intOrdenGasto { get; set; }
        public Nullable<int> intOrdenCompra { get; set; }
        public Nullable<int> intTipoGasto { get; set; }
        public Nullable<decimal> decCantidad { get; set; }
        public Nullable<int> intMoneda { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
        public Nullable<int> intPacking { get; set; }
        public Nullable<decimal> decGastoPesos { get; set; }
    
        public virtual tbOrdenCompraEnc tbOrdenCompraEnc { get; set; }
        public virtual tbPackingEnc tbPackingEnc { get; set; }
    }
}
