//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrdenCompraDesglose
    {
        public Nullable<int> intOCDetDesglose { get; set; }
        public int intOCDesglose { get; set; }
        public Nullable<int> intOrdenCompra { get; set; }
        public Nullable<int> intLineaOC { get; set; }
        public Nullable<int> intArticulo { get; set; }
        public Nullable<decimal> decCantidad { get; set; }
        public Nullable<int> intRelease { get; set; }
        public Nullable<int> intPartida { get; set; }
        public string strNumSerie { get; set; }
        public Nullable<int> intUbicacion { get; set; }
        public Nullable<bool> IsMarcado { get; set; }
        public Nullable<int> intAlmacen { get; set; }
        public Nullable<bool> IsIngresado { get; set; }
        public Nullable<int> intCantidad { get; set; }
        public Nullable<int> intOrdenDet { get; set; }
        public Nullable<int> intUnidadPresentacion { get; set; }
        public string strPrefijo { get; set; }
        public Nullable<int> intPacking { get; set; }
        public Nullable<int> intPresentacion { get; set; }
        public Nullable<bool> IsImpreso { get; set; }
        public string strUsuarioImprime { get; set; }
    
        public virtual tbOrdenCompraDetDesglose tbOrdenCompraDetDesglose { get; set; }
    }
}
