//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrdenCompraDet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbOrdenCompraDet()
        {
            this.tbOrdenCompraDetDesglose = new HashSet<tbOrdenCompraDetDesglose>();
        }
    
        public Nullable<int> intOrdenCompraEnc { get; set; }
        public int intOrdenCompraDetId { get; set; }
        public Nullable<int> intArticulo { get; set; }
        public Nullable<decimal> decCantidad { get; set; }
        public Nullable<bool> IsBorrado { get; set; }
        public Nullable<int> intLineaOC { get; set; }
        public Nullable<int> intUbicacion { get; set; }
        public Nullable<decimal> decArancel { get; set; }
        public Nullable<int> intMonedaArancel { get; set; }
        public Nullable<int> intArancel { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
        public string strDescripcion { get; set; }
        public Nullable<decimal> decPrecio { get; set; }
        public Nullable<int> intAlmacen { get; set; }
    
        public virtual tbOrdenCompraEnc tbOrdenCompraEnc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbOrdenCompraDetDesglose> tbOrdenCompraDetDesglose { get; set; }
    }
}
