//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrdenCompraDetDesglose
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbOrdenCompraDetDesglose()
        {
            this.tbOrdenCompraDesglose = new HashSet<tbOrdenCompraDesglose>();
        }
    
        public Nullable<int> intOrdenCompraDet { get; set; }
        public int intOCDetDesglose { get; set; }
        public Nullable<int> intOrdenCompra { get; set; }
        public Nullable<int> intLineaOC { get; set; }
        public Nullable<int> intCantidad { get; set; }
        public Nullable<decimal> decCantidad { get; set; }
        public Nullable<bool> IsBorrado { get; set; }
        public Nullable<int> intClasificacion { get; set; }
        public Nullable<int> intSubClasificacion { get; set; }
        public Nullable<int> intLinea { get; set; }
        public Nullable<int> intModelo { get; set; }
        public Nullable<int> intColor { get; set; }
        public Nullable<int> intPresentacion { get; set; }
        public Nullable<int> intRollos { get; set; }
        public Nullable<int> intArticulo { get; set; }
        public Nullable<int> intAlmacen { get; set; }
        public Nullable<int> intUbicacion { get; set; }
        public Nullable<int> intIngresado { get; set; }
        public Nullable<int> intUnidadPresentacion { get; set; }
        public Nullable<int> intPacking { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbOrdenCompraDesglose> tbOrdenCompraDesglose { get; set; }
        public virtual tbOrdenCompraDet tbOrdenCompraDet { get; set; }
    }
}
