//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrdenCompraEnc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbOrdenCompraEnc()
        {
            this.tbOrdenCompraDet = new HashSet<tbOrdenCompraDet>();
            this.tbOrdenGasto = new HashSet<tbOrdenGasto>();
        }
    
        public Nullable<int> intEmpresa { get; set; }
        public int intOrdenCompraEncId { get; set; }
        public Nullable<int> intProveedor { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public Nullable<decimal> decImporte { get; set; }
        public Nullable<bool> IsBorrado { get; set; }
        public string strObservaciones { get; set; }
        public Nullable<int> intOrdenCompra { get; set; }
        public Nullable<decimal> decTotalOrden { get; set; }
        public Nullable<decimal> decTipoCambio { get; set; }
        public Nullable<int> intAlmacen { get; set; }
        public string strOrigen { get; set; }
        public Nullable<System.DateTime> datFechaAnticipo { get; set; }
        public Nullable<System.DateTime> datFechaLiquidacion { get; set; }
        public string strFactura { get; set; }
        public Nullable<int> intEstatusOC { get; set; }
        public Nullable<int> intEstadoOC { get; set; }
        public Nullable<System.DateTime> datFechaEtiquetas { get; set; }
        public Nullable<int> intMoneda { get; set; }
        public Nullable<decimal> decIva { get; set; }
        public Nullable<int> intComprador { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
        public Nullable<System.DateTime> datFechaArribo { get; set; }
        public Nullable<bool> IsAprobado { get; set; }
        public Nullable<bool> IsConfirmado { get; set; }
    
        public virtual tbComprador tbComprador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbOrdenCompraDet> tbOrdenCompraDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbOrdenGasto> tbOrdenGasto { get; set; }
    }
}
