//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPartner
    {
        public int intPartnerId { get; set; }
        public string strNombre { get; set; }
        public string strNombreCorto { get; set; }
        public string strContacto { get; set; }
        public string strEmail { get; set; }
        public string strDireccion1 { get; set; }
        public string strDireccion2 { get; set; }
        public string strTelefono { get; set; }
        public string strRFC { get; set; }
        public Nullable<int> intMoneda { get; set; }
        public Nullable<int> intPais { get; set; }
        public Nullable<int> intCiudad { get; set; }
        public Nullable<bool> IsActivo { get; set; }
        public Nullable<bool> IsBorrado { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
    
        public virtual tbCiudades tbCiudades { get; set; }
        public virtual tbPaises tbPaises { get; set; }
    }
}
