//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProveedor
    {
        public Nullable<int> intEmpresa { get; set; }
        public int intProveedorId { get; set; }
        public string strNombre { get; set; }
        public string strDireccion1 { get; set; }
        public string strDireccion2 { get; set; }
        public string strDireccion3 { get; set; }
        public string strCodigoPostal { get; set; }
        public string strRFC { get; set; }
        public string strFax { get; set; }
        public string strTelefono { get; set; }
        public string strCodigoImpuestoRegion { get; set; }
        public Nullable<int> intPais { get; set; }
        public string strEmail { get; set; }
        public string strWebProveedor { get; set; }
        public Nullable<bool> IsBorrado { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
        public Nullable<int> intGrupoProv { get; set; }
        public Nullable<int> intMoneda { get; set; }
        public Nullable<int> intPlazo { get; set; }
        public Nullable<int> intLenguaje { get; set; }
        public string strCodigo { get; set; }
        public Nullable<int> intCiudad { get; set; }
        public string strComentarios { get; set; }
        public string strNombreCorto { get; set; }
        public string strPuertoOrigen { get; set; }
        public Nullable<int> intTiempoEspera { get; set; }
        public Nullable<decimal> decImpuesto { get; set; }
        public Nullable<int> intContactoPred { get; set; }
        public Nullable<bool> IsActivo { get; set; }
    }
}
