//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRegistroMovimiento
    {
        public Nullable<int> intEmpresa { get; set; }
        public int intMovimientoId { get; set; }
        public Nullable<int> intAlmacen { get; set; }
        public Nullable<int> intUbicacion { get; set; }
        public Nullable<int> intOrdenCompra { get; set; }
        public Nullable<int> intFactura { get; set; }
        public Nullable<int> intTipoMovimiento { get; set; }
        public Nullable<int> intArticulo { get; set; }
        public Nullable<decimal> decCantidad { get; set; }
        public string strNumSerie { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
        public Nullable<int> intSolicitudTrans { get; set; }
        public Nullable<int> intSolicitudTransDet { get; set; }
        public Nullable<decimal> decExistAntes { get; set; }
        public Nullable<decimal> decExistDespues { get; set; }
        public Nullable<int> intOrdenVenta { get; set; }
        public string strJob { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<decimal> decExistGlobal { get; set; }
        public string strComentario { get; set; }
        public Nullable<decimal> decTipoCambio { get; set; }
    }
}
