//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSolTransDetDesglose
    {
        public Nullable<int> intEmpresa { get; set; }
        public int intSolDetDesglose { get; set; }
        public Nullable<int> intSolicitudEnc { get; set; }
        public Nullable<int> intSolicitudDet { get; set; }
        public Nullable<int> intArticulo { get; set; }
        public string strNumSerie { get; set; }
        public Nullable<System.DateTime> datFechaEnvio { get; set; }
        public Nullable<System.DateTime> datFechaRecibido { get; set; }
        public Nullable<decimal> decCantidad { get; set; }
        public Nullable<bool> boolFueRecibido { get; set; }
        public string strNumeroSerie { get; set; }
        public Nullable<int> intExistenciaDet { get; set; }
    }
}
