//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSolicitudTransDet
    {
        public Nullable<int> intEmpresa { get; set; }
        public Nullable<int> intSolicitudEnc { get; set; }
        public int intSolicitudDet { get; set; }
        public Nullable<int> intEstatus { get; set; }
        public Nullable<int> intPartida { get; set; }
        public Nullable<int> intArticulo { get; set; }
        public Nullable<decimal> decCostoArticulo { get; set; }
        public Nullable<decimal> decCantidad { get; set; }
        public Nullable<decimal> decCostoPedido { get; set; }
        public Nullable<decimal> decEnviado { get; set; }
        public Nullable<decimal> decCostoEnviado { get; set; }
        public Nullable<decimal> decRecibido { get; set; }
        public Nullable<decimal> decCostoRecibido { get; set; }
        public Nullable<int> intAlmacen { get; set; }
        public Nullable<int> intUbicacion { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
        public Nullable<int> intEstatusRecibo { get; set; }
        public Nullable<int> intEstatusEnvio { get; set; }
    }
}
