//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTransferencia
    {
        public int intTransferencia { get; set; }
        public Nullable<int> intArticulo { get; set; }
        public string strSerie { get; set; }
        public Nullable<int> intCantidad { get; set; }
        public Nullable<int> intAlmacenSalida { get; set; }
        public Nullable<int> intAlmacenEntrada { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
        public Nullable<int> intEmpresa { get; set; }
    }
}
