//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUbicacion
    {
        public Nullable<int> intEmpresa { get; set; }
        public int intUbicacionId { get; set; }
        public Nullable<int> intAlmacen { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
        public Nullable<bool> IsBorrado { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string strDescripcion { get; set; }
        public string strBinNum { get; set; }
        public Nullable<int> intNegativos { get; set; }
        public Nullable<bool> IsActivo { get; set; }
    
        public virtual tbAlmacen tbAlmacen { get; set; }
    }
}
