//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebeasNetFrameWork_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUnidadMedidaConversion
    {
        public Nullable<int> intEmpresa { get; set; }
        public int intUMConversionId { get; set; }
        public string strUMClase { get; set; }
        public string strCodigoUM { get; set; }
        public Nullable<decimal> decFactorConversion { get; set; }
        public string strDescripcionUM { get; set; }
        public string strOperadorConversion { get; set; }
        public Nullable<int> intActivo { get; set; }
        public string strUsuarioAlta { get; set; }
        public string strMaquinaAlta { get; set; }
        public Nullable<System.DateTime> datFechaAlta { get; set; }
        public string strUsuarioMod { get; set; }
        public string strMaquinaMod { get; set; }
        public Nullable<System.DateTime> datFechaMod { get; set; }
        public Nullable<bool> IsBorrado { get; set; }
        public string strCodigoSat { get; set; }
    }
}
